openapi: 3.1.0
info:
  description: ""
  license:
    name: ""
  title: api
  version: 0.1.0
servers:
- url: /
paths:
  /audio_bibles:
    get:
      operationId: get_audio_bibles
      parameters:
      - explode: true
        in: query
        name: language
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: version
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAudioBiblesRes"
          description: ""
      tags: []
  /audio_bibles/{audio_bible_id}/books:
    get:
      operationId: get_audio_bible_books
      parameters:
      - explode: false
        in: path
        name: audio_bible_id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAudioBooksRes"
          description: ""
      tags: []
  /audio_bibles/{audio_bible_id}/books/{book_num}/chapters:
    get:
      operationId: get_audio_bible_chapters
      parameters:
      - explode: false
        in: path
        name: audio_bible_id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      - explode: false
        in: path
        name: book_num
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAudioChaptersRes"
          description: ""
      tags: []
  /audio_bibles/{audio_bible_id}/books/{book_num}/chapters/{chapter_num}:
    get:
      operationId: get_audio_chapter
      parameters:
      - explode: false
        in: path
        name: audio_bible_id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      - explode: false
        in: path
        name: book_num
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      - explode: false
        in: path
        name: chapter_num
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            audio/mpeg: {}
          description: Returns the audio chapter file
        "404":
          content:
            text/plain:
              schema:
                type: string
          description: Audio Chapter not found
      tags: []
  /bibles:
    get:
      operationId: get_bibles
      parameters:
      - explode: true
        in: query
        name: language
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: version
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBiblesRes"
          description: ""
      tags: []
  /bibles/{bible_id}/books:
    get:
      operationId: get_bible_books
      parameters:
      - explode: false
        in: path
        name: bible_id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBibleBooksRes"
          description: ""
      tags: []
  /bibles/{bible_id}/books/{book_num}/chapters:
    get:
      operationId: get_bible_chapters
      parameters:
      - explode: false
        in: path
        name: bible_id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      - explode: false
        in: path
        name: book_num
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBibleChaptersRes"
          description: ""
      tags: []
  /bibles/{bible_id}/books/{book_num}/chapters/{chapter_num}/verses:
    get:
      operationId: get_bible_verses
      parameters:
      - explode: true
        in: query
        name: start
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: end
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - explode: false
        in: path
        name: bible_id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      - explode: false
        in: path
        name: book_num
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      - explode: false
        in: path
        name: chapter_num
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBibleVersesRes"
          description: ""
      tags: []
  /bibles/{bible_id}/books/{book_num}/chapters/{chapter_num}/verses/{verse_num}:
    get:
      operationId: get_bible_verse_by_number
      parameters:
      - explode: false
        in: path
        name: bible_id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      - explode: false
        in: path
        name: book_num
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      - explode: false
        in: path
        name: chapter_num
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      - explode: false
        in: path
        name: verse_num
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BibleVerse"
          description: ""
      tags: []
  /health:
    get:
      operationId: get_health
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: ""
      tags: []
components:
  schemas:
    AudioBible:
      example:
        audio_bible_id: 0
        language: language
        version: version
      properties:
        audio_bible_id:
          format: int32
          type: integer
        language:
          type: string
        version:
          nullable: true
          type: string
      required:
      - audio_bible_id
      - language
    Bible:
      example:
        language: language
        bible_id: 0
        version: version
      properties:
        bible_id:
          format: int32
          type: integer
        language:
          type: string
        version:
          nullable: true
          type: string
      required:
      - bible_id
      - language
    BibleVerse:
      example:
        chapter: 1
        book: 6
        bible_id: 0
        text: text
        verse: 5
      properties:
        bible_id:
          format: int32
          type: integer
        book:
          format: int32
          type: integer
        chapter:
          format: int32
          type: integer
        text:
          type: string
        verse:
          format: int32
          type: integer
      required:
      - bible_id
      - book
      - chapter
      - text
      - verse
    GetAudioBiblesRes:
      example:
        audio_bibles:
        - audio_bible_id: 0
          language: language
          version: version
        - audio_bible_id: 0
          language: language
          version: version
      properties:
        audio_bibles:
          items:
            $ref: "#/components/schemas/AudioBible"
          type: array
      required:
      - audio_bibles
    GetAudioBooksRes:
      example:
        num_books: 0
      properties:
        num_books:
          format: int64
          type: integer
      required:
      - num_books
    GetAudioChaptersRes:
      example:
        num_chapters: 0
      properties:
        num_chapters:
          format: int64
          type: integer
      required:
      - num_chapters
    GetBibleBooksRes:
      example:
        num_books: 0
      properties:
        num_books:
          format: int64
          type: integer
      required:
      - num_books
    GetBibleChaptersRes:
      example:
        num_chapters: 0
      properties:
        num_chapters:
          format: int64
          type: integer
      required:
      - num_chapters
    GetBibleVersesRes:
      example:
        verses:
        - chapter: 1
          book: 6
          bible_id: 0
          text: text
          verse: 5
        - chapter: 1
          book: 6
          bible_id: 0
          text: text
          verse: 5
      properties:
        verses:
          items:
            $ref: "#/components/schemas/BibleVerse"
          type: array
      required:
      - verses
    GetBiblesRes:
      example:
        bibles:
        - language: language
          bible_id: 0
          version: version
        - language: language
          bible_id: 0
          version: version
      properties:
        bibles:
          items:
            $ref: "#/components/schemas/Bible"
          type: array
      required:
      - bibles
